apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 65.5.1
    helm:
      valuesObject:
        grafana:
          enabled: true
          adminPassword: "admin"
          service:
            type: ClusterIP
          ingress:
            enabled: true
            ingressClassName: alb
            annotations:
              alb.ingress.kubernetes.io/scheme: internet-facing
              alb.ingress.kubernetes.io/target-type: ip
              alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
              alb.ingress.kubernetes.io/ssl-redirect: '443'
              alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:106940013645:certificate/5ef596b8-f5a9-4e47-994c-38bd75d66de0
              alb.ingress.kubernetes.io/group.name: todolist
            hosts:
              - grafana.kodetechm.com
          persistence:
            enabled: true
            storageClassName: ebs-gp3-sc
            size: 5Gi
        prometheus:
          prometheusSpec:
            scrapeInterval: 15s
            evaluationInterval: 15s
            retention: 15d
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: ebs-gp3-sc
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 20Gi
        alertmanager:
          alertmanagerSpec:
            storage:
              volumeClaimTemplate:
                spec:
                  storageClassName: ebs-gp3-sc
                  resources:
                    requests:
                      storage: 2Gi
            secrets:
              - alert-manager-slack-webhhok
          config:
            global:
              slack_api_url_file: etc/alertmanager/secrets/alert-manager-slack-webhook/webhook-url
            route:
              receiver: "slack-notifications"
              group_by: ['alertname', 'namespace']
              group_wait: 30s
              group_interval: 5m
              repeat_interval: 1h
            receivers:
              - name: "slack-notifications"
                slack_Configs:
                  - channel: "#all-devops-institute"
                    send_Resolved: true
                    title: '{{`{{ .GroupLabels.alertname }}`}}'
                    text: '{{`{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}`}}'
            
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
        