apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"

spec:
  project: default
  source:
    repoURL: https://github.io
    chart: opentelemetry-operator
    targetRevision: 0.70.0
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true