apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 1.8.1
    helm:
      parameters:
        - name: clusterName
          value: mern-todo-cluster
        - name: serviceAccount.create
          value: "true"
        - name: serviceAccount.annotations.eks\.amazonaws\.com/role-arn
          value: arn:aws:iam::106940013645:role/mern-todo-cluster-alb-controller-9c1720f476674c2c6049e38e70
        - name: region
          value: ap-south-1
        - name: vpcId
          value: vpc-00a95d1993ee29e2d
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true