apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/autoscaler
    chart: cluster-autoscaler
    targetRevision: 9.37.0
    helm:
      parameters:
        - name: autoDiscovery.clusterName
          value: mern-todo-cluster
        - name: region
          value: ap-south-1
        - name: rbac.serviceAccount.annotations.eks\.amazonaws\.com/role-arn
          value: arn:aws:iam::106940013645:role/mern-todo-cluster-cluster-autoscaler-dfbdf0ad03c3adbea77d98a6d7
        - name: extraArgs.balance-similar-node-groups
          value: "true"
        - name: extraArgs.skip-nodes-with-system-pods
          value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true