apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/autoscaler
    chart: cluster-autoscaler
    targetRevision: 9.37.0
    helm:
      values: |
        
        autoDiscovery:
          clusterName: mern-todo-cluster
        cloudProvider: aws
        awsRegion: ap-south-1
        fullnameOverride: cluster-autoscaler

        rbac:
          create: true
          
        serviceAccount:
          create: true
          name: cluster-autoscaler
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::106940013645:role/todolist-cluster-cluster-autoscaler-adcb7a9a6d809d1b091b62d23d
        
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true